# Generated by Django 5.2.3 on 2025-06-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('News', 'News'), ('Event', 'Event')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(default='2025-01-01')),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
