# Generated by Django 5.2.3 on 2025-06-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='files',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
    ]
