# Generated by Django 5.2.3 on 2025-06-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_mediafile_mediagroup_delete_mediabatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('news', 'News'), ('event', 'Event')], max_length=10)),
                ('image', models.ImageField(upload_to='highlights/')),
                ('date', models.DateField()),
            ],
        ),
    ]
