# Generated by Django 5.2.6 on 2025-11-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_mediagroup_description_alter_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
