# Generated by Django 5.2.6 on 2025-11-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_highlight_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
